// Renders a branded, shareable redeem-code "card" image (PNG) for admins to
// send to customers. The card composites one of the BreakBPM splash artworks
// (shark / pool player / hustler) as the background — chosen DETERMINISTICALLY
// from the code so the same code always wears the same artwork, and so the
// recipient's watch profile background (server-resolved from the same code)
// matches their card. Also draws a QR code linking to the code's
// /redeem/<CODE> page, the BREAKBPM.COM wordmark (mirroring the home splash
// look), the pass tier, and the code itself.
//
// Everything is drawn onto a single <canvas> so we can export a clean PNG via
// toBlob — no DOM-snapshot library (and its font/CORS quirks) required. The QR
// is generated by qrcode.react's <QRCodeCanvas> and passed in as a source
// canvas to draw from.
import { VARIANT_IMAGE_URLS, backgroundVariantForKey } from "./backgroundVariants";

// Logical drawing size; the backing canvas is scaled up for crisp output.
const CARD_W = 1000;
const CARD_H = 560;
const SCALE = 2;

// Cache loaded images per URL so repeat cards reuse the decoded bitmap.
const imageCache = new Map<string, Promise<HTMLImageElement>>();

function loadImage(url: string): Promise<HTMLImageElement> {
  let p = imageCache.get(url);
  if (!p) {
    p = new Promise((resolve, reject) => {
      const img = new Image();
      img.onload = () => resolve(img);
      img.onerror = () => reject(new Error(`card background failed to load: ${url}`));
      img.src = url;
    });
    imageCache.set(url, p);
  }
  return p;
}

/**
 * Load the splash artwork for a card background. The artwork is chosen
 * deterministically from the code (via `backgroundVariantForKey`) so a code's
 * card always matches the recipient's server-resolved watch-profile background.
 */
export function loadCardBackground(code: string): Promise<HTMLImageElement> {
  const url = VARIANT_IMAGE_URLS[backgroundVariantForKey(code)];
  return loadImage(url);
}

/** Human-readable label for a pass tier, shown as a badge on the card. */
export function passKindLabel(kind: string): string {
  switch (kind) {
    case "day":
      return "DAY PASS";
    case "twoweek":
      return "14 DAY PASS";
    case "month":
      return "MONTH PASS";
    case "year":
      return "YEAR PASS";
    case "lifetime":
      return "LIFETIME PASS";
    default:
      return "PASS";
  }
}

/**
 * Build the live redeem URL for a code, matching the game-join QR convention:
 * window origin + app base path + /redeem/<CODE>. In production this resolves
 * to the deployed domain.
 */
export function redeemUrlFor(code: string): string {
  const base = `${window.location.origin}${import.meta.env.BASE_URL.replace(/\/$/, "")}`;
  return `${base}/redeem/${encodeURIComponent(code)}`;
}

/** Safe download filename for a code's card image. */
export function cardFilename(code: string): string {
  const safe = code.replace(/[^A-Za-z0-9_-]/g, "");
  return `breakbpm-${safe || "code"}.png`;
}

/**
 * Best-effort: ensure the canvas fonts are loaded before drawing so the
 * wordmark renders in VT323 rather than a fallback. Silently degrades to
 * system monospace if the Font Loading API is unavailable or fails.
 */
export async function ensureCardFonts(): Promise<void> {
  if (typeof document === "undefined" || !("fonts" in document)) return;
  try {
    await Promise.all([
      document.fonts.load('92px "VT323"', "BREAKBPM.COM 0123456789"),
      document.fonts.load('17px "Courier New"', "BILLIARDS"),
    ]);
  } catch {
    // Fall back to system fonts — drawing still proceeds.
  }
}

interface DrawOpts {
  code: string;
  kind: string;
  bgImg: HTMLImageElement;
  qrCanvas: HTMLCanvasElement;
}

/** Draw a rounded-rectangle path (no fill/stroke). */
function roundRectPath(
  ctx: CanvasRenderingContext2D,
  x: number,
  y: number,
  w: number,
  h: number,
  r: number,
): void {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.arcTo(x + w, y, x + w, y + h, r);
  ctx.arcTo(x + w, y + h, x, y + h, r);
  ctx.arcTo(x, y + h, x, y, r);
  ctx.arcTo(x, y, x + w, y, r);
  ctx.closePath();
}

/** Draw an image as a centered "cover" fill of the destination box. */
function drawCover(
  ctx: CanvasRenderingContext2D,
  img: HTMLImageElement,
  dw: number,
  dh: number,
): void {
  const imgRatio = img.width / img.height;
  const dstRatio = dw / dh;
  let sx: number, sy: number, sw: number, sh: number;
  if (imgRatio > dstRatio) {
    sh = img.height;
    sw = sh * dstRatio;
    sx = (img.width - sw) / 2;
    sy = 0;
  } else {
    sw = img.width;
    sh = sw / dstRatio;
    sx = 0;
    sy = (img.height - sh) / 2;
  }
  ctx.drawImage(img, sx, sy, sw, sh, 0, 0, dw, dh);
}

/**
 * Composite the full redeem card onto `canvas`. Sets the canvas size, so the
 * caller just needs to provide an empty <canvas> element.
 */
export function drawRedeemCard(canvas: HTMLCanvasElement, opts: DrawOpts): void {
  canvas.width = CARD_W * SCALE;
  canvas.height = CARD_H * SCALE;
  const ctx = canvas.getContext("2d");
  if (!ctx) return;
  ctx.save();
  ctx.scale(SCALE, SCALE);

  // 1) Splash-art background (cover).
  drawCover(ctx, opts.bgImg, CARD_W, CARD_H);

  // 2) Dark CRT-style overlay — lighter on the left (art shows through near
  //    the QR) and darker on the right so the green text stays legible.
  const overlay = ctx.createLinearGradient(0, 0, CARD_W, 0);
  overlay.addColorStop(0, "rgba(6,12,6,0.55)");
  overlay.addColorStop(0.42, "rgba(6,12,6,0.80)");
  overlay.addColorStop(1, "rgba(6,12,6,0.93)");
  ctx.fillStyle = overlay;
  ctx.fillRect(0, 0, CARD_W, CARD_H);

  // Thin phosphor-green frame (mirrors the splash rule color).
  ctx.strokeStyle = "#2a6a2a";
  ctx.lineWidth = 2;
  ctx.strokeRect(9, 9, CARD_W - 18, CARD_H - 18);

  // 3) QR in a white quiet-zone box on the left.
  const boxSize = 300;
  const boxX = 60;
  const boxY = (CARD_H - boxSize) / 2 - 14;
  roundRectPath(ctx, boxX, boxY, boxSize, boxSize, 14);
  ctx.fillStyle = "#ffffff";
  ctx.fill();
  const qrPad = 20;
  // The source QR canvas is rendered larger than this box (qrcode.react scales
  // its backing store by devicePixelRatio), so this is a downscale — keep
  // smoothing on for clean, uniform modules (nearest-neighbour drops edges).
  ctx.drawImage(
    opts.qrCanvas,
    boxX + qrPad,
    boxY + qrPad,
    boxSize - qrPad * 2,
    boxSize - qrPad * 2,
  );

  // Caption under the QR.
  ctx.fillStyle = "#7aba7a";
  ctx.font = '18px "Courier New", monospace';
  ctx.textAlign = "center";
  ctx.fillText("SCAN TO REDEEM", boxX + boxSize / 2, boxY + boxSize + 32);
  ctx.textAlign = "left";

  // 4) Right-hand text block.
  const rx = 416;
  const rightEdge = CARD_W - 56;

  // Wordmark: BREAK (white) + BPM (green) + .COM (muted green).
  ctx.textBaseline = "alphabetic";
  const wmY = 196;
  ctx.font = '92px "VT323", "Courier New", monospace';
  let x = rx;
  ctx.fillStyle = "#e8e8e8";
  ctx.fillText("BREAK", x, wmY);
  x += ctx.measureText("BREAK").width;
  ctx.fillStyle = "#00ff41";
  ctx.fillText("BPM", x, wmY);
  x += ctx.measureText("BPM").width;
  ctx.fillStyle = "#5a9a5a";
  ctx.font = '50px "VT323", "Courier New", monospace';
  ctx.fillText(".COM", x + 5, wmY);

  // Subtitle.
  ctx.fillStyle = "#5a9a5a";
  ctx.font = '17px "Courier New", monospace';
  ctx.fillText("BILLIARDS SCORE TRACKER & STATS", rx, wmY + 32);

  // Divider rule (fades to the right, like the splash).
  const rule = ctx.createLinearGradient(rx, 0, rightEdge, 0);
  rule.addColorStop(0, "#2a6a2a");
  rule.addColorStop(1, "rgba(42,106,42,0)");
  ctx.fillStyle = rule;
  ctx.fillRect(rx, wmY + 48, rightEdge - rx, 2);

  // Tier badge — filled green chip with dark text.
  const badge = passKindLabel(opts.kind);
  ctx.font = '27px "VT323", "Courier New", monospace';
  const badgeW = ctx.measureText(badge).width + 36;
  const badgeY = wmY + 74;
  roundRectPath(ctx, rx, badgeY, badgeW, 44, 6);
  ctx.fillStyle = "#00ff41";
  ctx.fill();
  ctx.fillStyle = "#06210a";
  ctx.textBaseline = "middle";
  ctx.fillText(badge, rx + 18, badgeY + 24);
  ctx.textBaseline = "alphabetic";

  // Redeem code.
  ctx.fillStyle = "#7aba7a";
  ctx.font = '15px "Courier New", monospace';
  ctx.fillText("YOUR REDEEM CODE", rx, badgeY + 90);
  ctx.fillStyle = "#e8e8e8";
  ctx.font = '44px "VT323", "Courier New", monospace';
  ctx.fillText(opts.code, rx, badgeY + 130);

  ctx.restore();
}

/** Trigger a browser download of the canvas as a PNG. */
export function downloadCanvas(canvas: HTMLCanvasElement, filename: string): void {
  canvas.toBlob((blob) => {
    if (!blob) return;
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
  }, "image/png");
}
