import { pgTable, text, timestamp, integer, uniqueIndex, index } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod/v4";

/**
 * Discount codes can issue a pass to a user when redeemed.
 * `grantsPassKind` says which pass tier the code grants.
 *
 * `issuedByUserId` + `issuedAt` are populated only for codes that were
 * generated by an end-user (e.g. the pass-holder Day-Pass gift flow, or an
 * admin minting a comp code). They stay NULL for boot-time seed codes so the
 * back-compat path is preserved.
 *
 * `issuerKind` discriminates which user-facing flow minted the row so the two
 * issuer flows never interfere with each other: "gift" rows belong to the
 * 12h-cooldown Day-Pass gift flow, "admin" rows are comp codes minted from the
 * admin generator, and NULL covers legacy/seed codes. The gift flow scopes its
 * cooldown/supersede/list queries to gift-or-NULL rows so admin codes (which
 * share `issuedByUserId`) can never be superseded or throttle the gift flow.
 */
export const discountCodesTable = pgTable(
  "discount_codes",
  {
    code: text("code").primaryKey(), // uppercase, e.g. "FREELIFETIME"
    grantsPassKind: text("grants_pass_kind").notNull(), // "day" | "month" | "year" | "lifetime" | "lucky_break"
    maxRedemptions: integer("max_redemptions"), // null = unlimited
    redemptionCount: integer("redemption_count").notNull().default(0),
    expiresAt: timestamp("expires_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    issuedByUserId: text("issued_by_user_id"),
    issuedAt: timestamp("issued_at", { withTimezone: true }),
    issuerKind: text("issuer_kind"), // "gift" | "admin" | null (legacy/seed)
    // Splash artwork stamped on the redeem card at generation time
    // ("shark" | "pool-player" | "hustler"). NULL = no artwork. This is the
    // single source of truth for both the printed card and the redeemer's
    // watch-profile background — chosen by the admin (checkbox) when minting,
    // not derived from the code string. The profile resolver maps a redeemed
    // pass back to this column via the pass's sourceRef.
    backgroundVariant: text("background_variant"),
  },
  (t) => [index("discount_codes_issuer_issued_at_idx").on(t.issuedByUserId, t.issuedAt)],
);

/**
 * One row per (code, userId). The unique index is the canonical guard
 * against double-redemption — concurrent requests fail at insert time with
 * a duplicate-key error rather than racing past a SELECT-then-INSERT check.
 */
export const discountRedemptionsTable = pgTable(
  "discount_redemptions",
  {
    id: text("id").primaryKey(),
    code: text("code")
      .notNull()
      .references(() => discountCodesTable.code, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    passId: text("pass_id").notNull(),
    redeemedAt: timestamp("redeemed_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => [uniqueIndex("discount_redemptions_code_user_unique").on(t.code, t.userId)],
);

export const insertDiscountCodeSchema = createInsertSchema(discountCodesTable).omit({
  createdAt: true,
  redemptionCount: true,
});
export type InsertDiscountCode = z.infer<typeof insertDiscountCodeSchema>;
export type DiscountCode = typeof discountCodesTable.$inferSelect;
export type DiscountRedemption = typeof discountRedemptionsTable.$inferSelect;
